name: antlr4dart
version: 0.8.0
author: Dominic Jack <thedomjack@gmail.com>
description: ANTLR4 runtime library for Dart.
homepage: https://github.com/jackd/antlr4dart-runtime.git

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies:
  collection: any
